export const ACCOUNT_AUTH_REQUEST = 'ACCOUNT_AUTH_REQUEST';
export const ACCOUNT_AUTH_SUCCESS = 'ACCOUNT_AUTH_SUCCESS';
export const ACCOUNT_AUTH_FAIL = 'ACCOUNT_AUTH_FAIL';

export const ACCOUNT_LOGIN_REQUEST = 'ACCOUNT_LOGIN_REQUEST';
export const ACCOUNT_LOGIN_SUCCESS = 'ACCOUNT_LOGIN_SUCCESS';
export const ACCOUNT_LOGIN_FAIL = 'ACCOUNT_LOGIN_FAIL';

export const ACCOUNT_REGISTRATION_REQUEST = 'ACCOUNT_REGISTRATION_REQUEST';
export const ACCOUNT_REGISTRATION_SUCCESS = 'ACCOUNT_REGISTRATION_SUCCESS';
export const ACCOUNT_REGISTRATION_FAIL = 'ACCOUNT_REGISTRATION_FAIL';

export const ACCOUNT_LOGOUT = 'ACCOUNT_LOGOUT';
